version: "3.9"

services:
  sqlwriter:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sqlwriter
    env_file:
      - ./.env
    environment:
      - PORT=8001
      - VANNA_CHROMA_DIR=/opt/sqlwriter/chroma_db
      - VANNA_CHROMA_COLLECTION=vanna_memory
      - LOG_LEVEL=DEBUG
    ports:
      - "8001:8001"
    volumes:
      - ./chroma_db:/opt/sqlwriter/chroma_db
    restart: unless-stopped

